version: "3.1"
services:
    www:
        build:
            context: ./
            dockerfile: ./www/Dockerfile
        ports: 
            - "80:80"
        restart: always
        container_name: www-php
        volumes:
            - ./html:/var/www/html
        links:
            - db
        networks:
            - default
    db:
        image: mysql:8.0
        ports: 
            - "3306:3306"
        container_name: mysql8
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: dbname
#            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
#            - ./dump:/docker-entrypoint-initdb.d
            - ./dump/dump.sql:/docker-entrypoint-initdb.d/dump.sql
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        container_name: phpmyadmin
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
volumes:
    persistent:
